// packages/esmf-vue/src/micro-frontend.vue
<script lang="ts" setup generic="P">
import { loadMicroFrontend, UnmountFn } from "esmf-js";
import { computed, getCurrentInstance, onMounted, onUnmounted, ref } from "vue";

const props = defineProps<{ moduleName: string; props?: P }>();
const emit = defineEmits<{
  loaded: [meta?: Record<string, unknown>];
  mounted: [];
  error: [error: unknown];
}>();

const errorListenerPresent = computed(() => !!getCurrentInstance()?.vnode.props?.error);

let unmount: UnmountFn | undefined;
const root = ref();
const status = ref<"loading" | "error" | "ok">("loading");

onMounted(async () => {
  try {
    const mf = await loadMicroFrontend(props.moduleName);
    emit("loaded", mf.meta);
    unmount = await mf.mount(root.value, props.props);
    status.value = "ok";
    emit("mounted");
  } catch (e) {
    status.value = "error";
    if (!errorListenerPresent.value)
      console.error(`[esmf] Failed to bootstrap micro-frontend: ${props.moduleName}\n`, e);
    emit("error", e);
  }
});

onUnmounted(() => {
  unmount?.();
});
</script>

<template>
  <div ref="root">
    <slot v-if="status === 'loading'" name="default" />
    <slot v-if="status === 'error'" name="error" />
  </div>
</template>

// packages/esmf-react/src/micro-frontend.tsx
import React, { HTMLAttributes, ReactNode, useEffect, useRef, useState } from "react";
import { loadMicroFrontend, UnmountFn } from "esmf-js";

type MicroFrontendProps<P> = {
  moduleName: string;
  props?: P;
  onLoaded?: (meta?: Record<string, unknown>) => void;
  onMounted?: () => void;
  onError?: (error: unknown) => void;
  children?: ReactNode;
  errorComponent?: ReactNode;
} & HTMLAttributes<HTMLDivElement>;

export function MicroFrontend<P = unknown>({
  moduleName,
  props,
  onLoaded,
  onMounted,
  onError,
  children,
  errorComponent,
  ...rest
}: MicroFrontendProps<P>) {
  const rootRef = useRef<HTMLDivElement>(null);
  const unmountRef = useRef<UnmountFn>(null);
  const [status, setStatus] = useState<"loading" | "error" | "ok">("loading");

  useEffect(() => {
    setStatus("loading");

    (async () => {
      try {
        const mf = await loadMicroFrontend(moduleName);
        onLoaded?.(mf.meta);

        setStatus("ok");
        await new Promise((r) => setTimeout(r, 2));

        unmountRef.current = await mf.mount(rootRef.current!, props);
        onMounted?.();
      } catch (e) {
        setStatus("error");
        if (!onError) console.error(`[esmf] Failed to bootstrap micro-frontend: ${moduleName}\n`, e);
        onError?.(e);
      }
    })();

    return () => unmountRef.current?.();
  }, [moduleName, props]);

  return (
    <>
      {status === "ok" && <div ref={rootRef} {...rest} />}
      {status === "loading" && <div {...rest}>{children}</div>}
      {status === "error" && <div {...rest}>{errorComponent}</div>}
    </>
  );
}
